


const { Telegraf, Markup } = require("telegraf");
const path = require("path");
const axios = require("axios");

// Replace 'YOUR_BOT_TOKEN' with your actual bot token
const bot = new Telegraf("6809279648:AAH9CZQIpgeVKZWhg3o2zVv0awic9ArJW7Q");

// Helper function to get the image path
const imagePath = (fileName) => path.join(__dirname, "images", fileName);

// Function to register the user
const registerUser = async (userId, username, inviterUsername = "") => {
  try {
    const response = await axios.post("https://walledb.onrender.com/api/Cluster0/register", {
      userId,
      inviterUsername,
      username,
    });
    return response.data;
  } catch (error) {
    console.error('Error registering user:', error);
    throw error;
  }
};

bot.start(async (ctx) => {
  const userId = ctx.from.username;
  const username = ctx.from.username || "there";
  const inviterUsername = ctx.payload || ""; // Extract inviter username from start payload if available

  try {
    await registerUser(userId, username, inviterUsername);
    ctx.replyWithPhoto(
      { source: imagePath("description.png") },
      {
        caption: `*Welcome, @${username}! to Wall-E Farm🌱*\n\nYou can now farm WallE points on Ton Blockchain and are entitled to revenues generated by \n*WallE!!, ensure you're holding a $WALLE*`,
        parse_mode: 'Markdown',
        reply_markup: {
          inline_keyboard: [
            [
              {
                text: "Play",
                web_app: { url: "https://walle-bot.vercel.app/" },
              },
              { text: "Join community", callback_data: "description.png", 
              web_app: { url: "https://t.me/walleonton" },
            },
            ],
          ],
        },
      }
    );
  } catch (error) {
    ctx.reply('Welcome Back!');
  }
});

bot.launch();

